#PBS -N vqvae_downsample4_k4096
#PBS -o /gdata/lirui/pbs/pbs_out/train_vqvae_downsample4_k4096.out
#PBS -e /gdata/lirui/pbs/pbs_out/train_vqvae_downsample4_k4096.err
#PBS -l nodes=1:gpus=2:d
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is 'date'
echo Directory is $PWD

echo This job runs on following nodes:
cat $PBS_NODEFILE
echo $PBS_NODEFILE

echo $PBS_GPUFILE
cat $PBS_GPUFILE

startdocker -P /gdata/lirui -D /gdata2/pengjl -u "--shm-size 64G" -c "python /gdata/lirui/project/vcl/vqvae/train_vqvae.py --downsample 4 --n_embed 4096 --save_path /gdata/lirui/models/vqvae/vqvae_d4_n4096.pth" bit:5000/lirui_torch1.5_cuda10.1
