#PBS -N dist_nl_l2_orivq_motion
#PBS -o /gdata/lirui/pbs/pbs_out/dist_nl_l2_orivq_motion.out
#PBS -e /gdata/lirui/pbs/pbs_out/dist_nl_l2_orivq_motion.err
#PBS -l nodes=1:gpus=4:q
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is 'date'
echo Directory is $PWD

echo This job runs on following nodes:
cat $PBS_NODEFILE
echo $PBS_NODEFILE

echo $PBS_GPUFILE
cat $PBS_GPUFILE

startdocker -P /gdata/lirui -D /gdata/lirui -u "--shm-size 64G" -c "bash /gdata/lirui/project/vcl/tools/dist_train.sh /gdata/lirui/project/vcl/configs/train/ypb/dist_nl_l2_orivq_motion.py 4" bit:5000/lirui_torch1.5_cuda10.1_corr
