#PBS -N test_label_pro
#PBS -o /gdata/lirui/pbs/pbs_out/test_label_pro.out
#PBS -e /gdata/lirui/pbs/pbs_out/test_label_pro.err
#PBS -l nodes=1:gpus=4:Q
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is 'date'
echo Directory is $PWD

echo This job runs on following nodes:
cat $PBS_NODEFILE
echo $PBS_NODEFILE

echo $PBS_GPUFILE
cat $PBS_GPUFILE

startdocker -P /gdata/lirui -D /gdata/lirui -u "--shm-size 64G" -c "bash /gdata/lirui/project/vcl/tools/dist_test.sh /gdata/lirui/project/vcl/configs/train/ypb/vqvae_mlm_d4_nemd2048_byol_dyt_nl_l2_fc_orivq_withbbox_random_v2_2.py 4" bit:5000/lirui_torch1.8_cuda11.1_corres
