#PBS -N mast_d4_l2_base_rgb
#PBS -o /gdata/lirui/pbs/pbs_out/mast_d4_l2_base_rgb.out
#PBS -e /gdata/lirui/pbs/pbs_out/mast_d4_l2_base_rgb.err
#PBS -l nodes=1:gpus=4:C
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is 'date'
echo Directory is $PWD

echo This job runs on following nodes:
cat $PBS_NODEFILE
echo $PBS_NODEFILE

echo $PBS_GPUFILE
cat $PBS_GPUFILE

startdocker -P /gdata/lirui -D /gdata/lirui -u "--shm-size 64G" -c "bash /gdata/lirui/project/vcl/tools/dist_train.sh /gdata/lirui/project/vcl/configs/train/ypb/mast_d4_l2_base_rgb.py 4" bit:5000/lirui_torch1.8_cuda11.1_corr
