#PBS -N r18_nc_sgd_cos_1600e_r2_1xNx2_ytvos_mast_2
#PBS -o /gdata/lirui/pbs/pbs_out/r18_nc_sgd_cos_1600e_r2_1xNx2_ytvos_mast_2.out
#PBS -e /gdata/lirui/pbs/pbs_out/r18_nc_sgd_cos_1600e_r2_1xNx2_ytvos_mast_2.err
#PBS -l nodes=1:gpus=4:C
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is 'date'
echo Directory is $PWD

echo This job runs on following nodes:
cat $PBS_NODEFILE
echo $PBS_NODEFILE

echo $PBS_GPUFILE
cat $PBS_GPUFILE

startdocker -P /gdata/lirui -D /gdata/lirui -u "--shm-size 64G" -c "bash /gdata/lirui/project/vcl/tools/dist_train.sh /gdata/lirui/project/vcl/configs/train/ypb/r18_nc_sgd_cos_1600e_r2_1xNx2_ytvos_mast_2.py 4" bit:5000/lirui_torch1.8_cuda11.1_corres
