#PBS -N exp_name
#PBS -o /gdata/lirui/pbs/pbs_out/exp_name.out
#PBS -e /gdata/lirui/pbs/pbs_out/exp_name.err
#PBS -l nodes=1:gpus=4:Q
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is 'date'
echo Directory is $PWD

echo This job runs on following nodes:
cat $PBS_NODEFILE
echo $PBS_NODEFILE

echo $PBS_GPUFILE
cat $PBS_GPUFILE

startdocker -P /gdata/lirui -D /gdata/lirui -u "--shm-size 64G" -c "bash /gdata/lirui/project/vcl/tools/dist_train.sh /gdata/lirui/project/vcl/configs/train/exp_name.py 4" docker_name
