#PBS -N test_label_pro
#PBS -l nodes=1:gpus=1:S
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is 'date'
echo Directory is $PWD

echo This job runs on following nodes:
cat $PBS_NODEFILE
echo $PBS_NODEFILE

echo $PBS_GPUFILE
cat $PBS_GPUFILE

startdocker -P /gdata/lirui -D /gdata/lirui -u "--shm-size 64G" -c "bash /gdata/lirui/project/vcl/tools/single_test.sh /gdata/lirui/project/vcl/configs/test/label_propagation_ypb.py /gdata/lirui/expdir/VCL/group_vqvae_tracker/vqvae_mlm_d4_nemd2048_ps5_fc_orivq/epoch_400.pth" bit:5000/lirui_torch1.5_cuda10.1_corr
