#PBS -N test_label_pro
#PBS -o /gdata/lirui/pbs/pbs_out/test_vqvae_mlm_d4_nemd2048_dyt_ps11_l2_fc_orivq.out
#PBS -e /gdata/lirui/pbs/pbs_out/test_vqvae_mlm_d4_nemd2048_dyt_ps11_l2_fc_orivq.err
#PBS -l nodes=1:gpus=1:S
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is 'date'
echo Directory is $PWD

echo This job runs on following nodes:
cat $PBS_NODEFILE
echo $PBS_NODEFILE

echo $PBS_GPUFILE
cat $PBS_GPUFILE

startdocker -P /gdata/lirui -D /gdata/lirui -u "--shm-size 64G" -c "bash /gdata/lirui/project/vcl/tools/dist_test.sh /gdata/lirui/project/vcl/configs/train/vqvae_mlm_d4_nemd2048_dyt_ps11_l2_fc_orivq.py 1" bit:5000/lirui_torch1.5_cuda10.1_corr
