#PBS -N train_pervq
#PBS -o /gdata/lirui/pbs/pbs_out/train_pervq.out
#PBS -e /gdata/lirui/pbs/pbs_out/train_pervq.err
#PBS -l nodes=1:gpus=1:s
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is 'date'
echo Directory is $PWD

echo This job runs on following nodes:
cat $PBS_NODEFILE
echo $PBS_NODEFILE

echo $PBS_GPUFILE
cat $PBS_GPUFILE

startdocker -P /gdata/lirui -D /gdata/lirui -u "--shm-size 64G" -c "bash /gdata/lirui/project/vcl/tools/dist_pervq.sh /gdata/lirui/project/vcl/configs/train/ypb/train_dry_run.py 1" bit:5000/lirui_torch1.8_cuda11.1_corres
