#PBS -N vqvae_mlm_d4_nemd2048_dyt_nl_l2_nofc_orivq_motion_area0.2
#PBS -o /gdata/lirui/pbs/pbs_out/vqvae_mlm_d4_nemd2048_dyt_nl_l2_nofc_orivq_motion_area0.2.out
#PBS -e /gdata/lirui/pbs/pbs_out/vqvae_mlm_d4_nemd2048_dyt_nl_l2_nofc_orivq_motion_area0.2.err
#PBS -l nodes=1:gpus=4:q
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is 'date'
echo Directory is $PWD

echo This job runs on following nodes:
cat $PBS_NODEFILE
echo $PBS_NODEFILE

echo $PBS_GPUFILE
cat $PBS_GPUFILE

startdocker -P /gdata/lirui -D /gdata/lirui -u "--shm-size 64G" -c "bash /gdata/lirui/project/vcl_v2/tools/dist_train.sh /gdata/lirui/project/vcl_v2/configs/train/ypb/vqvae_mlm_d4_nemd2048_dyt_nl_l2_nofc_orivq_motion_area0.2.py 4" bit:5000/lirui_torch1.8_cuda11.1_corr
