#PBS -N vqvae_mlm_v2_d4_nemd2048_dyt_nl_fc_orivq_res
#PBS -o /gdata/lirui/pbs/pbs_out/vqvae_mlm_v2_d4_nemd2048_dyt_nl_fc_orivq_res.out
#PBS -e /gdata/lirui/pbs/pbs_out/vqvae_mlm_v2_d4_nemd2048_dyt_nl_fc_orivq_res.err
#PBS -l nodes=1:gpus=4:Q
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is 'date'
echo Directory is $PWD

echo This job runs on following nodes:
cat $PBS_NODEFILE
echo $PBS_NODEFILE

echo $PBS_GPUFILE
cat $PBS_GPUFILE

startdocker -P /gdata/lirui -D /gdata/lirui -u "--shm-size 64G" -c "bash /gdata/lirui/project/vcl/tools/dist_train_v2.sh /gdata/lirui/project/vcl/configs/train/ypb/vqvae_mlm_v2_d4_nemd2048_dyt_nl_fc_orivq_res.py 4" bit:5000/lirui_torch1.5_cuda10.1_corr
